module.exports = {
  preset: "ts-jest",
  testEnvironment: "jsdom",
  // testEnvironment: 'jest-environment-jsdom',
  moduleNameMapper: {
    "^@configs/(.*)$": "<rootDir>/src/configs/$1",
    "^@apis/(.*)$": "<rootDir>/src/apis/$1",
    "^@components/(.*)$": "<rootDir>/src/components/$1",
    "^@layouts/(.*)$": "<rootDir>/src/layouts/$1",
    "^@services/(.*)$": "<rootDir>/src/services/$1",
    "^@pages/(.*)$": "<rootDir>/src/pages/$1",
    "^@assets/(.*)$": "<rootDir>/src/assets/$1",
    "^@styles/(.*)$": "<rootDir>/src/styles/$1",
    "^@state/(.*)$": "<rootDir>/src/state/$1",
    "^@utils/(.*)$": "<rootDir>/src/utilities/$1",
    "^@slices$": "<rootDir>/src/state/slices/index",
    "^@selectors$": "<rootDir>/src/state/selectors/index",
    "^@types$": "<rootDir>/src/types/index",
    "\\.(css|less|scss)$": "identity-obj-proxy",
  },
  setupFilesAfterEnv: ["@testing-library/jest-dom/extend-expect"],
  collectCoverage: true,
  coverageReporters: ["html", "text"],
};
